# Generated by Django 5.0.6 on 2024-07-03 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stage', '0004_post_member_alter_member_phone_alter_member_pointsum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='member',
        ),
        migrations.AddField(
            model_name='post',
            name='member',
            field=models.ManyToManyField(related_name='points', to='stage.member'),
        ),
    ]
