# Generated by Django 5.0.7 on 2024-07-25 23:29

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stage", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={"ordering": ["-start_time"]},
        ),
        migrations.RenameField(
            model_name="event",
            old_name="end",
            new_name="end_time",
        ),
        migrations.RenameField(
            model_name="event",
            old_name="start",
            new_name="start_time",
        ),
        migrations.RemoveField(
            model_name="event",
            name="attendee",
        ),
        migrations.RemoveField(
            model_name="event",
            name="is_upcoming",
        ),
        migrations.AddField(
            model_name="event",
            name="attendees",
            field=models.ManyToManyField(
                blank=True, related_name="events_attending", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="event",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name="event",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="location",
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name="event",
            name="title",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="member",
            name="class_standing",
            field=models.CharField(
                choices=[
                    ("Freshman", "Freshman"),
                    ("Sophomore", "Sophomore"),
                    ("Junior", "Junior"),
                    ("Senior", "Senior"),
                    ("Graduate", "Graduate"),
                ],
                default="Freshman",
                max_length=100,
            ),
        ),
    ]
