# Generated by Django 5.0.7 on 2024-08-13 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stage', '0002_auto_20240729_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
