# Generated by Django 5.0.6 on 2024-07-03 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stage', '0002_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='pointsum',
            field=models.IntegerField(default='000000000'),
        ),
    ]
